#! /bin/sh

# WALLPAPER
feh --bg-fill /home/kn1gh7/.wallpapers/wallpaper.jpg &

# MONITORS
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# CONFIGURATION
bspc config border_width         	2
bspc config window_gap          	12
bspc config -m focused top_padding	32
bspc config split_ratio          	0.5
bspc config single_monocle	 	false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config click_to_focus	 	true
bspc config focus_follows_pointer	true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# COLORS
bspc config active_border_color "#61AFEF"
bspc config focused_border_color "#61AFEF"
bspc config normal_border_color "#282C34"
bspc config presel_feedback_color "#61AFEF"

# WINDOW RULES
bspc rule -a feh state='floating'
bspc rule -a mpv state='floating'
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating

# AUTOSTART
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nm-applet > /dev/null || nm-applet &
picom &
dunst &
~/.config/bspwm/autostart &

